language: python
install:
  - pip install -r requirements.txt
  - npm install
script:
  - python3 generate.py

deploy:
  local_dir: docs
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  
  keep_history: true
  on:
    branch: master
